apiVersion: apps/v1
kind: Deployment
metadata:
  name: restarting-deployment
  labels:
    app: restarting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restarting
  template:
    metadata:
      labels:
        app: restarting
    spec:
      containers:
      - name: restarting-container
        image: pedominguezbr/crashing-pod-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: restarting-deployment
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: restarting

